#! /usr/bin/env python3

# -*- coding: utf-8 -*-
# LICENSE
#
# This file is part of mss_record.
#
# If you use mss_record in any program or publication, please inform and
# acknowledge its author Stefan Mertl (stefan@mertl-research.at).
#
# mss_record is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import argparse
import configparser
import logging
import logging.handlers
import os
import sys

import mss_record.core.recorder


def get_logger_handler(filename):
    ''' Create a logging format handler.
    '''
    ch = logging.handlers.RotatingFileHandler(filename, maxBytes = 1000000, backupCount = 10)
    formatter = logging.Formatter("#LOG# - %(asctime)s - %(process)d - %(threadName)s - %(levelname)s - %(name)s: %(message)s")
    ch.setFormatter(formatter)

    return ch


def load_configuration(filename):
    ''' Load the configuration from a file.
    '''
    parser = configparser.ConfigParser()
    parser.read(filename)

    config = {}
    config['log'] = {}
    config['log']['dir'] = parser.get('log', 'log_dir').strip()
    config['log']['filename'] = parser.get('log', 'log_filename').strip()
    config['log']['level'] = parser.get('log', 'log_level').strip()

    config['station'] = {}
    config['station']['network'] = parser.get('station', 'network').strip()
    config['station']['station_code'] = parser.get('station', 'station_code').strip()
    config['station']['location'] = parser.get('station', 'location').strip()
    channel_list = []
    cur_channel = parser.get('station', 'channel_1').strip()
    if cur_channel:
        channel_list.append(cur_channel)
    cur_channel = parser.get('station', 'channel_2').strip()
    if cur_channel:
        channel_list.append(cur_channel)
    cur_channel = parser.get('station', 'channel_3').strip()
    if cur_channel:
        channel_list.append(cur_channel)
    config['station']['channels'] = channel_list

    return config


if __name__ == '__main__':

    # Specify the configuration file using argpars.
    parser = argparse.ArgumentParser(description = 'mss_record')

    parser.add_argument('config_file', help = 'The path to the configuration file.',
                        type = str)
    args = parser.parse_args()

    # Read the INI formatted configuration file using configparser.
    config = load_configuration(args.config_file)

    # Setup a rotating file logger.
    log_filename = os.path.join(config['log']['dir'], config['log']['filename'])
    if not os.path.exists(config['log']['dir']):
        os.makedirs(config['log']['dir'])
    logger = logging.getLogger('mss_record')
    logger.setLevel(config['log']['level'])
    logger.addHandler(get_logger_handler(log_filename))


    # Create the recorder instance.
    recorder = mss_record.core.recorder.Recorder(network = config['station']['network'],
                                        station = config['station']['station_code'],
                                        location = config['station']['location'],
                                        channels = config['station']['channels'])

    # Check the system.
    working_servers = recorder.check_ntp()
    if not working_servers:
        logger.error("No working NTP servers found, exiting.")
        sys.exit()

    # - available ADCs
    # - access to destination folder for miniseed files
    # - internet connection

    # Interrupt response handler für die ADC erstellen.
    # Die ADCs mit 860 sps laufen lassen.
    # Eine schnelle I2C clock verwenden.

    # Zeitdauer testen 




